table fact_Project_Stock
	lineageTag: b78797be-bce0-4276-9c66-034bc99ca04a

	column Material
		dataType: int64
		formatString: 0
		lineageTag: c70187f6-37a2-4ce4-a0fc-8825292eb3f1
		summarizeBy: sum
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Plant ID'
		dataType: string
		lineageTag: 932baa47-727a-4c23-9d8f-40f668138b85
		summarizeBy: none
		sourceColumn: Plant ID

		annotation SummarizationSetBy = Automatic

	column 'Valuation Type'
		dataType: string
		lineageTag: 4b045d10-4950-4303-b4b6-cbc90ca11e89
		summarizeBy: none
		sourceColumn: Valuation Type

		annotation SummarizationSetBy = Automatic

	column 'Special Stock'
		dataType: string
		lineageTag: c0923e9e-a4f7-4ad9-9093-6e96fba3ab0d
		summarizeBy: none
		sourceColumn: Special Stock

		annotation SummarizationSetBy = Automatic

	column 'WBS LV2'
		dataType: string
		lineageTag: 9b1a0060-9f73-4f05-bcd0-3c7b6e100fb0
		summarizeBy: none
		sourceColumn: WBS LV2

		annotation SummarizationSetBy = Automatic

	column 'Total Stock'
		dataType: int64
		formatString: #,0
		lineageTag: 10e5e108-d7b7-44a5-88e8-c5c65fc0b752
		summarizeBy: sum
		sourceColumn: Total Stock

		annotation SummarizationSetBy = Automatic

	column 'Base Unit of Measure'
		dataType: string
		lineageTag: 40a840e1-f0d6-4e6b-95b0-8a487ca1829f
		summarizeBy: none
		sourceColumn: Base Unit of Measure

		annotation SummarizationSetBy = Automatic

	column 'Total Value'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5bd92f2b-05c4-4290-a101-10c83ed51543
		summarizeBy: sum
		sourceColumn: Total Value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 848bb3e1-fad3-47b6-81ca-4ef915875c47
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column 'WBS LV1'
		dataType: string
		lineageTag: dc854969-f89a-42c7-8380-6a7e48790058
		summarizeBy: none
		sourceColumn: WBS LV1

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 8d5ce96e-4742-4b5e-ab51-f408f7b991fc
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Project Definition'
		dataType: string
		lineageTag: 7353f020-9490-43c2-a792-444a2d3ca20d
		summarizeBy: none
		sourceColumn: Project Definition

		annotation SummarizationSetBy = Automatic

	column 'Material Description'
		dataType: string
		lineageTag: 59161137-9ef6-4867-b2df-300db4e344a2
		summarizeBy: none
		sourceColumn: Material Description

		annotation SummarizationSetBy = Automatic

	partition fact_Project_Stock = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"Project Stock" = #"NED Overview Files"{[Name="Project Stock"]}[Content],
				    #"Project Stock 1 30 2025 XLSX" = #"Project Stock"{[Name="Project Stock 1.30.2025.XLSX"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Project Stock 1 30 2025 XLSX"),
				    Sheet1_Sheet = #"Imported Excel Workbook"{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Material", Int64.Type}, {"Valuation Area", type text}, {"Valuation Type", type text}, {"Special Stock", type text}, {"WBS Element", type text}, {"Total Stock", Int64.Type}, {"Base Unit of Measure", type text}, {"Total Value", type number}, {"Currency", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Material", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"WBS Element", "WBS LV2"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "WBS LV2", "WBS LV2 - Copy"),
				    #"Extracted First Characters" = Table.TransformColumns(#"Duplicated Column", {{"WBS LV2 - Copy", each Text.Start(_, 11), type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Extracted First Characters",{{"WBS LV2 - Copy", "WBS LV1"}, {"Valuation Area", "Plant ID"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","error","N/A",Replacer.ReplaceText,{"Material Description"}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Replaced Value", {{"Material Description", "N/A"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Errors",{{"Material", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each true),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows",null,"N/A",Replacer.ReplaceValue,{"Valuation Type"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

