table fact_Labor_Costs
	excludeFromModelRefresh
	lineageTag: 0fd2e92f-89c6-4508-8def-9c04f1993ba9

	column 'Project Definition'
		dataType: string
		lineageTag: 44c6a2ee-a472-4357-954a-849378840f7f
		summarizeBy: none
		sourceColumn: Project Definition

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'WBS Element'
		dataType: string
		lineageTag: 586bc5a9-20bd-4e8a-bc8f-765db8d62a3c
		summarizeBy: none
		sourceColumn: WBS Element

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FEB
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b1732f00-aecc-4e27-b23f-00a08d1725f6
		summarizeBy: sum
		sourceColumn: FEB

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MAR
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 24b67745-1538-42c1-bea2-bf5bc5f06d81
		summarizeBy: sum
		sourceColumn: MAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 01e73bfc-9c2f-4b19-9881-1145a4ec2786
		summarizeBy: sum
		sourceColumn: APR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SEP
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f936968a-7e28-4d32-b104-7a78bfd2358e
		summarizeBy: sum
		sourceColumn: SEP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OCT
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 437403d7-e8f7-43f3-9e69-4c77ede59e42
		summarizeBy: sum
		sourceColumn: OCT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cost Element'
		dataType: int64
		formatString: 0
		lineageTag: 249587de-80ad-425a-bc43-0a93fcadec43
		summarizeBy: sum
		sourceColumn: Cost Element

		annotation SummarizationSetBy = Automatic

	column 'Cost element descr.'
		dataType: string
		lineageTag: d65f7861-083d-47dd-a1f1-649f79612029
		summarizeBy: none
		sourceColumn: Cost element descr.

		annotation SummarizationSetBy = Automatic

	column JAN
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 032bc0de-2c70-40f3-8052-d8217f50c112
		summarizeBy: sum
		sourceColumn: JAN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column NOV
		dataType: double
		lineageTag: f29bc468-4f80-4d78-8876-844e87fc1da8
		summarizeBy: sum
		sourceColumn: NOV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DEC
		dataType: double
		lineageTag: 6d8bb465-b0c1-493c-a575-b0289d8a3bf3
		summarizeBy: sum
		sourceColumn: DEC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column13
		dataType: string
		lineageTag: 383a035f-77d8-436e-828a-d9898d905391
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 19c13678-a690-42d7-bdd9-4e7e6fcf0ca0
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 446b356b-62ef-4e20-aab1-3d1cfae31d68
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 88c431c0-82d3-4961-9bac-fe0b372f073e
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: ee5160e1-dd95-4a40-a6c7-cad802604727
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 2b5d4eeb-c1ae-4bfc-9073-f20c92204493
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: fcb727e2-7043-43a2-89f8-f47110831e8f
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: e1cff505-0c82-4868-87bf-6b2683aeccda
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	partition fact_Labor_Costs = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"Labor Charges" = #"NED Overview Files"{[Name="Labor Charges"]}[Content],
				    #"Maximo - Hours with Personnel wNames xlsx" = #"Labor Charges"{[Name="Maximo - Hours with Personnel wNames.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Maximo - Hours with Personnel wNames xlsx"),
				    #"Cost Element_Sheet" = #"Imported Excel Workbook"{[Item="Cost Element",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Cost Element_Sheet",3),
				    #"Removed Top Rows1" = Table.Skip(#"Removed Top Rows",2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows1", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Project Definition", type text}, {"WBS Element", type text}, {"Cost Element", Int64.Type}, {"Cost element descr.", type text}, {"Column5", type number}, {"Column6", type number}, {"Column7", type number}, {"Column8", type number}, {"Column9", type number}, {"Column10", type number}, {"Column11", type number}, {"Column12", type number}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column5", "JAN"}, {"Column6", "FEB"}, {"Column7", "MAR"}, {"Column8", "APR"}, {"Column9", "SEP"}, {"Column10", "OCT"}, {"Column11", "NOV"}, {"Column12", "DEC"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

