table fact_MB51
	lineageTag: fa08b29a-dc96-4bab-99a2-53abb79df339

	column Material
		dataType: string
		lineageTag: 966e48dd-c13a-4573-8cb6-d44d9c10c22e
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Plant ID '
		dataType: string
		lineageTag: 0aaf9636-eb48-4c63-843e-e35503c2c920
		summarizeBy: none
		sourceColumn: "Plant ID "

		annotation SummarizationSetBy = Automatic

	column 'Storage Location'
		dataType: string
		lineageTag: 0194bcf0-278f-425e-ace3-34f50f88f008
		summarizeBy: none
		sourceColumn: Storage Location

		annotation SummarizationSetBy = Automatic

	column 'Movement Type'
		dataType: int64
		formatString: 0
		lineageTag: 9a66d5f2-6c0b-4f09-806e-8b1b44e47d59
		summarizeBy: none
		sourceColumn: Movement Type

		annotation SummarizationSetBy = User

	column 'Special Stock'
		dataType: string
		lineageTag: 6206146f-609b-4eab-a05e-ad65166b277e
		summarizeBy: none
		sourceColumn: Special Stock

		annotation SummarizationSetBy = Automatic

	column 'Material Document'
		dataType: int64
		formatString: 0
		lineageTag: 4346f858-6189-4929-9e7d-15e81af57fb0
		summarizeBy: none
		sourceColumn: Material Document

		annotation SummarizationSetBy = User

	column 'Material Doc.Item'
		dataType: int64
		formatString: 0
		lineageTag: 2a86fa29-888c-4921-8896-af78a8072bbb
		summarizeBy: none
		sourceColumn: Material Doc.Item

		annotation SummarizationSetBy = User

	column 'Posting Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 28445828-a33f-4500-a6d3-6ee440936f85
		summarizeBy: none
		sourceColumn: Posting Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Qty in Un. of Entry'
		dataType: int64
		formatString: 0
		lineageTag: 18e4d376-eeea-43fa-85ec-c9151597e0fe
		summarizeBy: sum
		sourceColumn: Qty in Un. of Entry

		annotation SummarizationSetBy = Automatic

	column 'Unit of Entry'
		dataType: string
		lineageTag: f6416b80-f0fd-4ac8-9cf5-695af34c4faf
		summarizeBy: none
		sourceColumn: Unit of Entry

		annotation SummarizationSetBy = Automatic

	column 'Material Description'
		dataType: string
		lineageTag: a282f441-0289-4ac1-b269-ced6524cfbc0
		summarizeBy: none
		sourceColumn: Material Description

		annotation SummarizationSetBy = Automatic

	column Reservation
		dataType: int64
		formatString: 0
		lineageTag: ebc84c7c-97d6-4a03-b7da-c6816f42393d
		summarizeBy: none
		sourceColumn: Reservation

		annotation SummarizationSetBy = User

	column Order
		dataType: int64
		formatString: 0
		lineageTag: ff846d26-af96-4a0f-b941-fa994ab171a6
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'Cost Center'
		dataType: int64
		formatString: 0
		lineageTag: 8ccba2c8-9546-4249-b90f-2a79c0a50103
		summarizeBy: none
		sourceColumn: Cost Center

		annotation SummarizationSetBy = User

	column 'WBS LV2'
		dataType: string
		lineageTag: cce9a9c5-0546-4682-b830-8762ba7d44d3
		summarizeBy: none
		sourceColumn: WBS LV2

		annotation SummarizationSetBy = Automatic

	column 'User name'
		dataType: string
		lineageTag: ac260ced-8939-4d08-b86f-34bb6d61f6b5
		summarizeBy: none
		sourceColumn: User name

		annotation SummarizationSetBy = Automatic

	column 'Time of Entry'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f22b7a9-b6dc-4c72-a8e3-fca2df31e964
		summarizeBy: none
		sourceColumn: Time of Entry

		annotation SummarizationSetBy = Automatic

	column 'Amount in LC'
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 86f31e84-840d-4eab-9a39-3e198f299cfb
		summarizeBy: sum
		sourceColumn: Amount in LC

		annotation SummarizationSetBy = Automatic

	column 'WBS LV1'
		dataType: string
		lineageTag: 2406c6f6-c572-4bd9-a733-0b607787ef35
		summarizeBy: none
		sourceColumn: WBS LV1

		annotation SummarizationSetBy = Automatic

	partition fact_MB51 = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"MB51 - Material Details" = #"NED Overview Files"{[Name="MB51 - Material Details"]}[Content],
				    #"MB51 1 30 2025 XLSX" = #"MB51 - Material Details"{[Name="MB51 1.30.2025.XLSX"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"MB51 1 30 2025 XLSX"),
				    Sheet1_Sheet = #"Imported Excel Workbook"{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Material", Int64.Type}, {"Plant", type text}, {"Storage Location", type text}, {"Movement Type", Int64.Type}, {"Special Stock", type text}, {"Material Document", Int64.Type}, {"Material Doc.Item", Int64.Type}, {"Posting Date", type date}, {"Qty in Un. of Entry", Int64.Type}, {"Unit of Entry", type text}, {"Material Description", type text}, {"Reservation", Int64.Type}, {"Order", Int64.Type}, {"Cost Center", Int64.Type}, {"WBS Element", type text}, {"User name", type text}, {"Time of Entry", type datetime}, {"Amount in LC", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Material", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"WBS Element", "WBS LV2"}, {"Plant", "Plant ID "}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "WBS LV2", "WBS LV2 - Copy"),
				    #"Extracted First Characters" = Table.TransformColumns(#"Duplicated Column", {{"WBS LV2 - Copy", each Text.Start(_, 11), type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Extracted First Characters",{{"WBS LV2 - Copy", "WBS LV1"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

