table 'SAP L1, L2 Pivot'
	lineageTag: 0c11015b-9ed6-49cc-ae18-6e471f0a5717

	measure 'Variance L2' = CALCULATE(SUM(fact_L2[FY Level 2 Budget])- SUM('SAP L1, L2 Pivot'[Actuals Sum]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: df664985-c01d-41e2-be14-9202300e7cf4

	column 'WBS Element'
		dataType: string
		lineageTag: e7e2ccb6-f6c5-4212-b3fc-16de3ddeb8e5
		summarizeBy: none
		sourceColumn: WBS Element

		annotation SummarizationSetBy = Automatic

	column 'Project Definition'
		dataType: string
		lineageTag: b08c8b99-6b5d-48f5-8a47-3ffa8d44c29f
		summarizeBy: none
		sourceColumn: Project Definition

		annotation SummarizationSetBy = Automatic

	column Oct
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2c2a4271-a985-45f0-8701-74fc65eb0057
		summarizeBy: sum
		sourceColumn: Oct

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Nov
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bebb8207-a42f-4a82-8539-435315b8066d
		summarizeBy: sum
		sourceColumn: Nov

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Dec
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 69461488-effb-4209-abec-b5e07ba3c43e
		summarizeBy: sum
		sourceColumn: Dec

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Jan
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8c5805ce-91e4-4697-b6c9-f3d48fe72402
		summarizeBy: sum
		sourceColumn: Jan

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Feb
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 58d3b5b9-e8cc-4ffc-9df2-aebc8aa26f53
		summarizeBy: sum
		sourceColumn: Feb

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Mar
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3412cd6a-9dbe-49a2-9aaa-8a1774ae8f1d
		summarizeBy: sum
		sourceColumn: Mar

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Actuals Sum' = 'SAP L1, L2 Pivot'[Oct]+'SAP L1, L2 Pivot'[Nov]+'SAP L1, L2 Pivot'[Dec]+'SAP L1, L2 Pivot'[Jan]+'SAP L1, L2 Pivot'[Feb]+'SAP L1, L2 Pivot'[Mar]
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0cb7b46f-e82e-4206-bf31-6f41c4469435
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'VARINACE L2' = 'SAP L1, L2 Pivot'[BUDGET L2] - 'SAP L1, L2 Pivot'[Actuals Sum]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 863f7289-2991-4190-95f7-7e5d07aa1f48
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Apr
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 20bb5b9e-8fd5-497f-8f78-39c18cc9dea0
		summarizeBy: sum
		sourceColumn: Apr

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column May
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0e8145e7-5a6e-4d61-9a9c-16e7267d7e78
		summarizeBy: sum
		sourceColumn: May

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Jun
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9f843d08-1c53-4ec6-b775-abd45ebedaab
		summarizeBy: sum
		sourceColumn: Jun

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Column15
		dataType: string
		lineageTag: 16446885-35d4-40c3-9a3c-609980eaa78c
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: f23899ff-7bed-468d-b5f0-1045993d131e
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 8b794ab5-b48a-4a69-b8d6-93c3b1fffc15
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Jul
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a0deeb14-f7f1-4fb0-a122-5bbb3d9014d6
		summarizeBy: sum
		sourceColumn: Jul

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Aug
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 260174a4-f21a-4bb4-8239-fd843c294b79
		summarizeBy: sum
		sourceColumn: Aug

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Sep
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f721736a-cf13-4859-801a-31b36db4c7c3
		summarizeBy: sum
		sourceColumn: Sep

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'SAP L1, L2 Pivot' = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"SAP L1, L2" = #"NED Overview Files"{[Name="SAP L1, L2"]}[Content],
				    #"SAP L1, L2 XLSX" = #"SAP L1, L2"{[Name="SAP L1, L2.XLSX"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"SAP L1, L2 XLSX"),
				    Sheet4_Sheet = #"Imported Excel Workbook"{[Item="Sheet4",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Sheet4_Sheet,2),
				    #"Removed Top Rows1" = Table.Skip(#"Removed Top Rows",2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows1", [PromoteAllScalars=true]),
				    #"Filtered Rows" = Table.SelectRows(#"Promoted Headers", each ([WBS Element] <> null and [WBS Element] <> "Grand Total")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Column125", "Column100"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Columns",{"Column124", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123"})
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

