table 'Track Production'
	lineageTag: d7c7aea1-9e3a-416a-89bd-99d6a29bd4b3

	column AMTWORKREPORTINGID
		dataType: int64
		formatString: 0
		lineageTag: 383be4fb-c46c-44b4-a1b9-ed323a36d79d
		summarizeBy: count
		sourceColumn: AMTWORKREPORTINGID

		annotation SummarizationSetBy = Automatic

	column 'Work Order Number'
		dataType: int64
		formatString: 0
		lineageTag: b9b906a1-7f97-4480-a786-a25cd7263bac
		summarizeBy: sum
		sourceColumn: Work Order Number

		annotation SummarizationSetBy = Automatic

	column 'Work Order Description'
		dataType: string
		lineageTag: 13eb6440-879e-459e-80c7-4e55d4729277
		summarizeBy: none
		sourceColumn: Work Order Description

		annotation SummarizationSetBy = Automatic

	column 'WORK DATE'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3d8a6cc6-c81e-49da-9b86-ce5f7e15ebe2
		summarizeBy: none
		sourceColumn: WORK DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'WBS Element'
		dataType: string
		lineageTag: e30bdb13-3547-4fd4-8019-2b0c9bb0f6ea
		summarizeBy: none
		sourceColumn: WBS Element

		annotation SummarizationSetBy = Automatic

	column 'WBS  lv1'
		dataType: string
		lineageTag: 094e5910-c3c0-4848-8436-828b70198d98
		summarizeBy: none
		sourceColumn: WBS  lv1

		annotation SummarizationSetBy = Automatic

	column 'WBS Element Description'
		dataType: string
		lineageTag: 0feb6e7a-dd87-4d40-a738-fd4ac2cee4a7
		summarizeBy: none
		sourceColumn: WBS Element Description

		annotation SummarizationSetBy = Automatic

	column 'Long Name'
		dataType: string
		lineageTag: 9a6f227f-9146-47d1-94f3-71474ff35ad0
		summarizeBy: none
		sourceColumn: Long Name

		annotation SummarizationSetBy = Automatic

	column 'WORK Code'
		dataType: int64
		formatString: 0
		lineageTag: b431c984-b3bd-4767-a684-5f94f43e2f72
		summarizeBy: count
		sourceColumn: WORK Code

		annotation SummarizationSetBy = Automatic

	column 'WORK Code Description'
		dataType: string
		lineageTag: 601d6d08-8f1d-4764-9e9c-7a902bb3f50a
		summarizeBy: none
		sourceColumn: WORK Code Description

		annotation SummarizationSetBy = Automatic

	column Gang
		dataType: string
		lineageTag: 3f7c3c01-3b42-4861-8513-629481d38ae8
		summarizeBy: none
		sourceColumn: Gang

		annotation SummarizationSetBy = Automatic

	column 'Prod Qty'
		dataType: int64
		formatString: 0
		lineageTag: 966f5d10-ad25-4fcd-8f79-c907ec94a095
		summarizeBy: sum
		sourceColumn: Prod Qty

		annotation SummarizationSetBy = Automatic

	column 'Prod Unit'
		dataType: string
		lineageTag: 454fd22c-812e-4a02-b7c7-7b8199067265
		summarizeBy: none
		sourceColumn: Prod Unit

		annotation SummarizationSetBy = Automatic

	column 'Entered-BY Cost Center'
		dataType: int64
		formatString: 0
		lineageTag: 1fba8ffd-4b0b-41e2-b56d-20fb14a876ff
		summarizeBy: sum
		sourceColumn: Entered-BY Cost Center

		annotation SummarizationSetBy = Automatic

	column TRACKSTART
		dataType: string
		lineageTag: 74e4da7f-beb5-412a-9c2c-d1ebb5ad9861
		summarizeBy: none
		sourceColumn: TRACKSTART

		annotation SummarizationSetBy = Automatic

	column STARTLC
		dataType: string
		lineageTag: 3c4431c6-15ce-442d-96ff-43c8537afd9a
		summarizeBy: none
		sourceColumn: STARTLC

		annotation SummarizationSetBy = Automatic

	column STARTMEASUREMILEPOST
		dataType: double
		lineageTag: 20f73f1b-0603-43f7-95d8-337693c41a08
		summarizeBy: sum
		sourceColumn: STARTMEASUREMILEPOST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STARTMEASUREMILEPOSTOFFSET
		dataType: int64
		formatString: 0
		lineageTag: 6122c7d8-8ce8-4834-9928-9a29e4b13ea0
		summarizeBy: sum
		sourceColumn: STARTMEASUREMILEPOSTOFFSET

		annotation SummarizationSetBy = Automatic

	column STARTMEASUREMILEPOSTRELATIVE
		dataType: double
		lineageTag: 2607beed-bca7-44a0-83b6-9a27a2bd6a13
		summarizeBy: sum
		sourceColumn: STARTMEASUREMILEPOSTRELATIVE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENDMEASUREMILEPOST
		dataType: double
		lineageTag: 8e415ef9-6aa9-45bf-9315-79726c6dd606
		summarizeBy: sum
		sourceColumn: ENDMEASUREMILEPOST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENDMEASUREMILEPOSTOFFSET
		dataType: int64
		formatString: 0
		lineageTag: 8cb25b56-7cb4-48b7-92f9-2e7b7bf4c782
		summarizeBy: sum
		sourceColumn: ENDMEASUREMILEPOSTOFFSET

		annotation SummarizationSetBy = Automatic

	column ENDMEASUREMILEPOSTRELATIVE
		dataType: double
		lineageTag: 401150f5-04cc-4a86-a649-ef2cde2de979
		summarizeBy: sum
		sourceColumn: ENDMEASUREMILEPOSTRELATIVE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FUNCTION
		dataType: int64
		formatString: 0
		lineageTag: 0b489ede-317a-4021-8e01-9598bc17b4d6
		summarizeBy: sum
		sourceColumn: FUNCTION

		annotation SummarizationSetBy = Automatic

	column 'WORK MONTH'
		dataType: string
		lineageTag: 2d0259ea-f3be-40fa-81c4-455d1592cd5f
		summarizeBy: none
		sourceColumn: WORK MONTH

		annotation SummarizationSetBy = Automatic

	column 'WORK DAY'
		dataType: int64
		formatString: 0
		lineageTag: fd6e2f31-411a-4225-b756-ebd2f8322a33
		summarizeBy: sum
		sourceColumn: WORK DAY

		annotation SummarizationSetBy = Automatic

	column 'WORK YEAR'
		dataType: int64
		formatString: 0
		lineageTag: 4de0c137-f3a8-4ac6-9abb-9bf8a85afd20
		summarizeBy: sum
		sourceColumn: WORK YEAR

		annotation SummarizationSetBy = Automatic

	column Detail_Capital_Segment
		dataType: string
		lineageTag: 63859b17-b9d8-46be-84e0-049e76ee3427
		summarizeBy: none
		sourceColumn: Detail_Capital_Segment

		annotation SummarizationSetBy = Automatic

	column Asset
		dataType: string
		lineageTag: 93b826f6-fef6-4ef4-acdf-43db8fd5dae4
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	column 'Task Manager'
		dataType: int64
		formatString: 0
		lineageTag: 5a8b66ea-4a5c-4002-9eab-f3b3192de700
		summarizeBy: sum
		sourceColumn: Task Manager

		annotation SummarizationSetBy = Automatic

	column Column30
		dataType: string
		lineageTag: d4b61854-48b1-41b8-8c7d-e9e2ba517ab8
		summarizeBy: none
		sourceColumn: Column30

		annotation SummarizationSetBy = Automatic

	partition 'Track Production' = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"01-Project_Directory" = General{[Name="01-Project_Directory"]}[Content],
				    #"C EN 101842-STIP-NewEnglandTrackProgram" = #"01-Project_Directory"{[Name="C.EN.101842-STIP-NewEnglandTrackProgram"]}[Content],
				    #"8000-STIP-NEDTrackProgramManagement" = #"C EN 101842-STIP-NewEnglandTrackProgram"{[Name="8000-STIP-NEDTrackProgramManagement"]}[Content],
				    ProgramWorkbooks = #"8000-STIP-NEDTrackProgramManagement"{[Name="ProgramWorkbooks"]}[Content],
				    #"FY 25" = ProgramWorkbooks{[Name="FY 25"]}[Content],
				    #"New England Track Workbook FY25 xlsx" = #"FY 25"{[Name="New England Track Workbook FY25.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"New England Track Workbook FY25 xlsx"),
				    #"Actuals - Production_Sheet" = #"Imported Excel Workbook"{[Item="Actuals - Production",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Actuals - Production_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"AMTWORKREPORTINGID", Int64.Type}, {"Work Order Number", Int64.Type}, {"Work Order Description", type text}, {"WORK DATE", type date}, {"WBS Element", type text}, {"WBS  lv1", type text}, {"WBS Element Description", type text}, {"Long Name", type text}, {"WORK Code", Int64.Type}, {"WORK Code Description", type text}, {"Gang", type text}, {"Prod Qty", Int64.Type}, {"Prod Unit", type text}, {"Entered-BY Cost Center", Int64.Type}, {"TRACKSTART", type any}, {"STARTLC", type text}, {"STARTMEASUREMILEPOST", type number}, {"STARTMEASUREMILEPOSTOFFSET", Int64.Type}, {"STARTMEASUREMILEPOSTRELATIVE", type number}, {"ENDMEASUREMILEPOST", type number}, {"ENDMEASUREMILEPOSTOFFSET", Int64.Type}, {"ENDMEASUREMILEPOSTRELATIVE", type number}, {"FUNCTION", Int64.Type}, {"WORK MONTH", type text}, {"WORK DAY", Int64.Type}, {"WORK YEAR", Int64.Type}, {"Detail_Capital_Segment", type text}, {"Asset", type text}, {"Task Manager", Int64.Type}, {"Column30", type any}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([WBS  lv1] = "C.EN.101842"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

