table 'Track Summary'
	lineageTag: 0502ca4e-abe0-4f0d-94d3-773f62985ae2

	measure '% Spent' =
			
			DIVIDE(
				SUM('Track Summary'[FY25 Actuals]),
				SUM('Track Summary'[ Budget])
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: fea3867c-fcbb-4eac-ace1-ea8baac495b2

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure '% Complete' =
			
			DIVIDE(
				SUM('Track Summary'[FY25 Qty Actuals]),
				SUM('Track Summary'[FY25 Qty Planned])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ff134b59-ba2b-4a36-9e46-a54618c4f0e4

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	column 'Asset Type'
		dataType: string
		lineageTag: 9530ff07-3420-47ef-b50f-4ac87d346c6d
		summarizeBy: none
		sourceColumn: Asset Type

		annotation SummarizationSetBy = Automatic

	column ' Budget'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 885e2aa9-41a8-46e1-b405-134579d67bcf
		summarizeBy: none
		sourceColumn: " Budget"

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'FY25 Actuals'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c059bbf0-7e48-4c02-83b7-3a25575a8704
		summarizeBy: none
		sourceColumn: FY25 Actuals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Percent Spent'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5339a292-242a-486e-bbc6-7ef4f14d000b
		summarizeBy: none
		sourceColumn: Percent Spent

		annotation SummarizationSetBy = Automatic

	column 'FY25 Qty Planned'
		dataType: int64
		formatString: #,0
		lineageTag: 3a57ac2c-f85c-418e-8b59-38781f2b6d6c
		summarizeBy: none
		sourceColumn: FY25 Qty Planned

		annotation SummarizationSetBy = Automatic

	column 'FY25 Qty Actuals'
		dataType: int64
		formatString: #,0
		lineageTag: 8d8d2a8e-22f6-4c64-a829-72475de73d83
		summarizeBy: none
		sourceColumn: FY25 Qty Actuals

		annotation SummarizationSetBy = Automatic

	column ' Percent Complete'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d270069c-98a8-447c-8ebd-5807daa0d7f2
		summarizeBy: none
		sourceColumn: " Percent Complete"

		annotation SummarizationSetBy = Automatic

	partition 'Track Summary' = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"01-Project_Directory" = General{[Name="01-Project_Directory"]}[Content],
				    #"C EN 101842-STIP-NewEnglandTrackProgram" = #"01-Project_Directory"{[Name="C.EN.101842-STIP-NewEnglandTrackProgram"]}[Content],
				    #"8000-STIP-NEDTrackProgramManagement" = #"C EN 101842-STIP-NewEnglandTrackProgram"{[Name="8000-STIP-NEDTrackProgramManagement"]}[Content],
				    ProgramWorkbooks = #"8000-STIP-NEDTrackProgramManagement"{[Name="ProgramWorkbooks"]}[Content],
				    #"FY 25" = ProgramWorkbooks{[Name="FY 25"]}[Content],
				    #"New England Track Workbook FY25 xlsx" = #"FY 25"{[Name="New England Track Workbook FY25.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"New England Track Workbook FY25 xlsx"),
				    #"Monthly PP_Sheet" = #"Imported Excel Workbook"{[Item="Monthly PP",Kind="Sheet"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Monthly PP_Sheet",{"Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17"}),
				    #"Removed Top Rows" = Table.Skip(#"Removed Columns",2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Asset Type", type text}, {" Budget", Currency.Type}, {"FY25 Actuals", Currency.Type}, {"Percent Spent", Percentage.Type}, {"FY25 Qty Planned", Int64.Type}, {"FY25 Qty Actuals", Int64.Type}, {" Percent Complete", Percentage.Type}, {"Column8", type text}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type",10),
				    #"Removed Bottom Rows1" = Table.RemoveLastN(#"Removed Bottom Rows",15),
				    #"Removed Bottom Rows2" = Table.RemoveLastN(#"Removed Bottom Rows1",2),
				    #"Removed Bottom Rows3" = Table.RemoveLastN(#"Removed Bottom Rows2",1),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Bottom Rows3",{"Column8"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns1", each ([Asset Type] <> null and [Asset Type] <> "Overall "))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

