table dim_Plant_ID_Details
	lineageTag: e7f47cb0-bd09-499e-9d31-d5c96a91ad67

	column 'Plant ID'
		dataType: string
		lineageTag: 684afe92-cd28-4e30-98c7-bb95700d84d8
		summarizeBy: none
		sourceColumn: Plant ID

		annotation SummarizationSetBy = Automatic

	column 'Plant Name'
		dataType: string
		lineageTag: d1eb0bd3-e24a-4731-a88d-fbd478246db4
		summarizeBy: none
		sourceColumn: Plant Name

		annotation SummarizationSetBy = Automatic

	column Street
		dataType: string
		lineageTag: 8e95746c-f948-4e09-bf76-12d24055adef
		summarizeBy: none
		sourceColumn: Street

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 9c0f0e64-e586-464f-aefa-b9a9e4e0ed72
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 101b1c4c-fd7c-470c-9007-f7b3d0b8280e
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: f524b998-b1de-491b-a1c0-ef4222b12e3c
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition dim_Plant_ID_Details = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"Plant ID xlsx" = #"NED Overview Files"{[Name="Plant ID.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Plant ID xlsx"),
				    Table1_Table = #"Imported Excel Workbook"{[Item="Table1",Kind="Table"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(Table1_Table,null,"N/A",Replacer.ReplaceValue,{"Plant Name"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

