table dim_Work_Codes
	lineageTag: 6d3ca221-df67-47ce-8cd4-96a4088e67a1

	column 'WBS LV2'
		dataType: string
		lineageTag: 0631195d-07e3-4af9-a501-e0a4c41a5124
		summarizeBy: none
		sourceColumn: WBS LV2

		annotation SummarizationSetBy = Automatic

	column 'WBS LV1 '
		dataType: string
		lineageTag: 13c8e4f6-1dda-4d82-a8b3-682a9da20007
		summarizeBy: none
		sourceColumn: "WBS LV1 "

		annotation SummarizationSetBy = Automatic

	column WBS_LV2_Description
		dataType: string
		lineageTag: af63f29a-2f69-4eb6-aada-c7a73fb1a6ce
		summarizeBy: none
		sourceColumn: WBS_LV2_Description

		annotation SummarizationSetBy = Automatic

	column Maximo_Work_Order
		dataType: int64
		formatString: 0
		lineageTag: 5efd1767-b832-4961-b2b2-a677035f0684
		summarizeBy: none
		sourceColumn: Maximo_Work_Order

		annotation SummarizationSetBy = User

	column Maximo_Work_Code
		dataType: int64
		formatString: 0
		lineageTag: 4a0c701f-9649-4db2-8d55-bf26e389d8d9
		summarizeBy: none
		sourceColumn: Maximo_Work_Code

		annotation SummarizationSetBy = User

	column Maximo_Work_Code_Description
		dataType: string
		lineageTag: f9276f11-6bcb-47c9-a685-ea939488ab41
		summarizeBy: none
		sourceColumn: Maximo_Work_Code_Description

		annotation SummarizationSetBy = Automatic

	partition dim_Work_Codes = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"09-Portfolio_Workbooks" = General{[Name="09-Portfolio_Workbooks"]}[Content],
				    #"NortheastPortfolio-Data-Level2Maximo xlsx" = #"09-Portfolio_Workbooks"{[Name="NortheastPortfolio-Data-Level2Maximo.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"NortheastPortfolio-Data-Level2Maximo xlsx"),
				    #"Filtered Rows" = Table.SelectRows(#"Imported Excel Workbook", each ([Name] = "NortheastPortfolio-Data-Level2M")),
				    #"NortheastPortfolio-Data-Level2M_Sheet" = #"Filtered Rows"{[Item="NortheastPortfolio-Data-Level2M",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"NortheastPortfolio-Data-Level2M_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"WBS_Element", type text}, {"SAP_Number", type text}, {"WBS_Description", type text}, {"Maximo_Work_Order", Int64.Type}, {"Maximo_Work_Code", type any}, {"Maximo_Work_Code_Description", type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each true),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows1",{{"Maximo_Work_Code", Int64.Type}, {"Maximo_Work_Order", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"WBS_Element", "WBS LV2"}, {"SAP_Number", "WBS LV1 "}, {"WBS_Description", "WBS_LV2_Description"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

