table fact_Ariba_PO
	lineageTag: 538a3659-f46b-46b7-be4b-7d10c16ab635

	column 'WBS LV2'
		dataType: string
		lineageTag: ccdbfb4b-1e55-4e6e-a7e1-c18e61f212a9
		summarizeBy: none
		sourceColumn: WBS LV2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'WBSElement LV2'
		dataType: string
		lineageTag: cf2ff27e-db92-4891-a696-1ff38dc27653
		summarizeBy: none
		sourceColumn: WBSElement LV2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Requester (User)'
		dataType: string
		lineageTag: 27f8a13a-c03f-4275-a585-5059763488aa
		summarizeBy: none
		sourceColumn: Requester (User)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GL Account Id'
		dataType: int64
		formatString: 0
		lineageTag: 62559444-653e-4b7c-9025-2066cbe10e17
		summarizeBy: count
		sourceColumn: GL Account Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cost Center ID'
		dataType: int64
		formatString: 0
		lineageTag: aea0ef43-0349-479f-9560-f1230966f13f
		summarizeBy: none
		sourceColumn: Cost Center ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO Id'
		dataType: string
		lineageTag: 6bff3398-b6f0-441a-a690-4e4003e5bce7
		summarizeBy: none
		sourceColumn: PO Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Requisition Title'
		dataType: string
		lineageTag: 9e644541-8d06-48df-b2b8-14958cba88a0
		summarizeBy: none
		sourceColumn: Requisition Title

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO Line Number'
		dataType: int64
		formatString: 0
		lineageTag: 93b03f3d-598a-4aae-bd4a-9eae24412460
		summarizeBy: none
		sourceColumn: PO Line Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Requisition Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ff3b9d8e-ee3e-47ba-81b2-cb16c1b95b93
		summarizeBy: none
		sourceColumn: Requisition Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Requisition ID'
		dataType: string
		lineageTag: 43427753-44bd-48d5-b7e5-ac80ce226c47
		summarizeBy: none
		sourceColumn: Requisition ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Requisition Status'
		dataType: string
		lineageTag: fd9ddf6a-5048-4ad1-b46e-fb1f1c853f70
		summarizeBy: none
		sourceColumn: Requisition Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Requisition Description'
		dataType: string
		lineageTag: f4c0762d-1f87-4b78-966b-176373febe62
		summarizeBy: none
		sourceColumn: Requisition Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO Description'
		dataType: string
		lineageTag: 73575459-27bc-4693-afd2-88331f866e48
		summarizeBy: none
		sourceColumn: PO Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO Ordered Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 673dbaa3-bce8-4791-b527-c381d9c7cf74
		summarizeBy: none
		sourceColumn: PO Ordered Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'PO Status'
		dataType: string
		lineageTag: 0155596f-bfb4-4fd4-b74d-ccedd5f458cd
		summarizeBy: none
		sourceColumn: PO Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[PO]Closed Order Status'
		dataType: string
		lineageTag: 9dabaf35-2dc9-48a3-9778-7c0d7d56c220
		summarizeBy: none
		sourceColumn: [PO]Closed Order Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[PO]Supplier (ERP Supplier ID)'
		dataType: int64
		formatString: 0
		lineageTag: c4e9743a-c4c3-4ae8-a6c9-0baea3e7eb58
		summarizeBy: none
		sourceColumn: [PO]Supplier (ERP Supplier ID)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column '[PO]Supplier (ERP Supplier)'
		dataType: string
		lineageTag: 47b3160a-8ea1-4b54-bebf-1dcfd12e0fd4
		summarizeBy: none
		sourceColumn: [PO]Supplier (ERP Supplier)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column [PO]Contract
		dataType: string
		lineageTag: 2905f0a4-f505-4094-8458-0fed4517d03f
		summarizeBy: none
		sourceColumn: [PO]Contract

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[PO]Contract Id'
		dataType: string
		lineageTag: 1bc8fe93-e518-4ccb-9049-ac1dbac9e303
		summarizeBy: none
		sourceColumn: [PO]Contract Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[PO]Contract Expiration Date'
		dataType: string
		lineageTag: c68ba2c5-b7b6-48c3-91b7-12eb9af7c246
		summarizeBy: none
		sourceColumn: [PO]Contract Expiration Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column [ACC]Contract
		dataType: string
		lineageTag: 94b0cd20-f9b9-4615-9b5c-28cf6ac4757c
		summarizeBy: none
		sourceColumn: [ACC]Contract

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[ACC]Contract Id'
		dataType: string
		lineageTag: b07ae12c-fae6-4b06-9735-158ba3499dd1
		summarizeBy: none
		sourceColumn: [ACC]Contract Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[ACC (RLS)] COTR'
		dataType: string
		lineageTag: 74c50ba1-0c30-43ed-ab04-265c5216c3b2
		summarizeBy: none
		sourceColumn: [ACC (RLS)] COTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[PO] Purchasing Group (Purchase Organization Id)'
		dataType: int64
		formatString: 0
		lineageTag: fe5cbf49-bb47-4455-b9ee-b5416d2e67af
		summarizeBy: sum
		sourceColumn: [PO] Purchasing Group (Purchase Organization Id)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '[PO]Purchasing Group (Purchase Organization)'
		dataType: string
		lineageTag: df473ebc-b955-4698-bc5d-0233acac43a0
		summarizeBy: none
		sourceColumn: [PO]Purchasing Group (Purchase Organization)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Requisition Spend'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 81fe47e6-51d3-47c8-81b9-a9eea08cd520
		summarizeBy: sum
		sourceColumn: Requisition Spend

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PO Spend'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a6f2c6cf-e4c0-4392-b479-6f486455165b
		summarizeBy: sum
		sourceColumn: PO Spend

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Amount Accepted'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 180e2f50-1917-420c-a795-43c5ea8fcc19
		summarizeBy: sum
		sourceColumn: Amount Accepted

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Amount Invoiced'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 56df3eb1-fe94-419c-856d-0291ac959c48
		summarizeBy: sum
		sourceColumn: Amount Invoiced

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Amount Left to Invoice Total'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c386bd51-6b50-41f5-89c8-71e37937e7e9
		summarizeBy: sum
		sourceColumn: Amount Left to Invoice Total

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'sum(Amount Invoiced)2'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 92520e74-e53d-4eb7-bd1e-60fa59288e9a
		summarizeBy: sum
		sourceColumn: sum(Amount Invoiced)2

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'WBS LV1'
		dataType: string
		lineageTag: 0ab3b5bb-3967-4810-994c-e9bc1073a36d
		summarizeBy: none
		sourceColumn: WBS LV1

		annotation SummarizationSetBy = Automatic

	partition fact_Ariba_PO = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"Ariba PO" = #"NED Overview Files"{[Name="Ariba PO"]}[Content],
				    #"PO Report JAN6 xlsx" = #"Ariba PO"{[Name="PO Report FEB11.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"PO Report JAN6 xlsx"),
				    #"PO Report by WBS or Cost Center_Sheet" = #"Imported Excel Workbook"{[Item="PO Report by WBS or Cost Center",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"PO Report by WBS or Cost Center_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"[REQ]WBSElement (WBSElement Id)", type text}, {"[REQ]WBSElement (WBSElement)", type text}, {"[REQ]Requester (User)", type text}, {"[REQ]GL Account (GL Account Id)", Int64.Type}, {"[REQ]Cost Center (Cost center ID)", Int64.Type}, {"[PO] Order Id", type any}, {"[REQ] Requisition Title", type text}, {"[PO] PO Line Number", Int64.Type}, {"[REQ]Requisition Date (Date)", type date}, {"[REQ] Requisition ID", type text}, {"[REQ] Requisition Status", type text}, {"[REQ] Description", type text}, {"[PO] Description", type text}, {"[PO]Ordered Date (Date)", type date}, {"[PO] PO Status", type text}, {"[PO] Closed Order Status", type text}, {"[PO]Supplier (ERP Supplier ID)", Int64.Type}, {"[PO]Supplier (ERP Supplier)", type text}, {"[PO]Contract (Contract)", type text}, {"[PO]Contract (Contract Id)", type text}, {"[PO]Contract (Expiration Date)", type any}, {"[ACC]Contract (Contract)", type text}, {"[ACC]Contract (Contract Id)", type text}, {"[ACC (RLS)] COTR", type text}, {"[PO]Purchasing Group (Purchase Organization Id)", Int64.Type}, {"[PO]Purchasing Group (Purchase Organization)", type text}, {"sum(Requisition Spend)", type number}, {"sum(PO Spend)", type number}, {"sum(Amount Accepted)", type number}, {"sum(Amount Invoiced)", type number}, {"sum(Amount Left to Invoice Total)", type number}, {"sum(Amount Invoiced)2", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"[REQ]WBSElement (WBSElement Id)", "WBS LV2"}, {"[PO] Order Id", "PO Id"}, {"[PO]Ordered Date (Date)", "PO Ordered Date"}, {"[REQ] Requisition Title", "Requisition Title"}, {"[REQ]Cost Center (Cost center ID)", "Cost Center ID"}, {"[REQ]GL Account (GL Account Id)", "GL Account Id"}, {"[REQ]Requester (User)", "Requester (User)"}, {"[PO] PO Line Number", "PO Line Number"}, {"[REQ]WBSElement (WBSElement)", "WBSElement LV2"}, {"[REQ]Requisition Date (Date)", "Requisition Date"}, {"[REQ] Requisition ID", "Requisition ID"}, {"[REQ] Requisition Status", "Requisition Status"}, {"[REQ] Description", "Requisition Description"}, {"[PO] Description", "PO Description"}, {"[PO] PO Status", "PO Status"}, {"[PO] Closed Order Status", "[PO]Closed Order Status"}, {"[PO]Contract (Contract)", "[PO]Contract"}, {"[PO]Contract (Contract Id)", "[PO]Contract Id"}, {"[PO]Contract (Expiration Date)", "[PO]Contract Expiration Date"}, {"[ACC]Contract (Contract)", "[ACC]Contract"}, {"[ACC]Contract (Contract Id)", "[ACC]Contract Id"}, {"[PO]Purchasing Group (Purchase Organization Id)", "[PO] Purchasing Group (Purchase Organization Id)"}, {"sum(Requisition Spend)", "Requisition Spend"}, {"sum(PO Spend)", "PO Spend"}, {"sum(Amount Accepted)", "Amount Accepted"}, {"sum(Amount Invoiced)", "Amount Invoiced"}, {"sum(Amount Left to Invoice Total)", "Amount Left to Invoice Total"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "WBS LV2", "WBS LV2 - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"WBS LV2 - Copy", "WBS LV1"}}),
				    #"Inserted First Characters" = Table.AddColumn(#"Renamed Columns1", "First Characters", each Text.Start([WBS LV1], 11), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted First Characters",{"WBS LV1"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"First Characters", "WBS LV1"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns2",{"WBS LV1", "WBS LV2", "WBSElement LV2", "Requester (User)", "GL Account Id", "Cost Center ID", "PO Id", "Requisition Title", "PO Line Number", "Requisition Date", "Requisition ID", "Requisition Status", "Requisition Description", "PO Description", "PO Ordered Date", "PO Status", "[PO]Closed Order Status", "[PO]Supplier (ERP Supplier ID)", "[PO]Supplier (ERP Supplier)", "[PO]Contract", "[PO]Contract Id", "[PO]Contract Expiration Date", "[ACC]Contract", "[ACC]Contract Id", "[ACC (RLS)] COTR", "[PO] Purchasing Group (Purchase Organization Id)", "[PO]Purchasing Group (Purchase Organization)", "Requisition Spend", "PO Spend", "Amount Accepted", "Amount Invoiced", "Amount Left to Invoice Total", "sum(Amount Invoiced)2"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns","(CW2233892) Randstad - IT _ Marketing Staff Augmentation MSA - CW","Randstad - IT _ Marketing Staff Augmentation MSA",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","(CW2229097) C1092 (Legacy BPO1001601) Loram Maintenance of Way","Loram Maintenance of Way",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","(CW2237104) Wood and Concrete Tie_Timber Removal Services (BPO1003774)","Wood & Concrete Tie_Timber Removal Services ",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","(CW2237030) AE Facilities NED Primary - WSP","AE Facilities NED Primary - WSP",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","(LCW97159) Material Inspection Services - Applied Testing and Geosciences BPO1003933","Material Inspection Services - Applied Testing and Geosciences ",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","(CW2231888) Misc Steel Fabrication Contract","Misc Steel Fabrication Contract",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","(CW2237002) AE Bridges NED Primary - HNTB","AE Bridges NED Primary - HNTB",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","(CW2231137) 111 Kahrimanian - Contractors Supply"," Kahrimanian - Contractors Supply",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","(CW2246074) MSA Baycrane Crane with Operator Service","MSA Baycrane Crane with Operator Service",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","(CW2237006) AE Bridges NED Secondary - STV","AE Bridges NED Secondary - STV",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","(CW2249271) 010- ELECTRICAL WHOLESALERS","ELECTRICAL WHOLESALERS",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","(LCW102514) AECOM Master CM Contract BPO1004332","AECOM Master CM ",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","(CW2231192) Catenary Aluminum SAP Assembly blanket agreement","Catenary Aluminum SAP Assembly blanket agreement",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","(CW2248519) TILCON CT - BALLAST - CONNECTICUT REGION","TILCON CT - BALLAST - CONNECTICUT REGION",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","(CW2248363) SM Lorusso - Stone and Ballast for New England area","SM Lorusso - Stone and Ballast for New England area",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","(CW2238406) Empire Engineering Ballast","Empire Engineering Ballast",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","(CW2243541) 139 Robert Brown - All-Lifts","Robert Brown - All-Lifts",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","(CW2257562) 010-GRANITE CITY","GRANITE CITY",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","(CW2249944) 010 HARTMAN- REDS BUILDING SUPPLIES LLC"," HARTMAN- REDS BUILDING SUPPLIES LLC",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","(CW2249489) 111 Kahrimanian - HUB Federal Signs","Kahrimanian - HUB Federal Signs",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","(CW2256652) 157_Portable Restroom and Janitorial Svcs","Portable Restroom and Janitorial Svcs",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","(CW2237323) WSP System Track Design Support Services MSA"," WSP System Track Design Support Services MSA",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","(LCW71594) WARWINK INDUSTRIAL FASTENER - BPO1002395 BPO1002395","WARWINK INDUSTRIAL FASTENER ",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","(LCW95636) 058 Chamberlin AECOM Environmental Contract BPO697","Chamberlin AECOM Environmental Contract",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value23", each true),
				    #"Replaced Value24" = Table.ReplaceValue(#"Filtered Rows","(CW2231803) 111 Kahrimanian - Quincy Compressor","Kahrimanian - Quincy Compressor",Replacer.ReplaceText,{"[PO]Contract"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value24", each true)
				in
				    #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

