table fact_Labor_details
	lineageTag: d1b0e750-add7-4219-ae51-e7cd8237e3eb

	column 'Document Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: fd36a38e-2fcf-496b-bbbe-707740350196
		summarizeBy: none
		sourceColumn: Document Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Posting Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6d58d0ed-43ff-4862-bd0b-7c9f9b4965d0
		summarizeBy: none
		sourceColumn: Posting Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'WBS LV1'
		dataType: string
		lineageTag: 45b60dea-9d5e-4d33-ae4c-7367d142a941
		summarizeBy: none
		sourceColumn: WBS LV1

		annotation SummarizationSetBy = Automatic

	column 'WBS Element LV2'
		dataType: string
		lineageTag: 82bd6d0e-5ec8-468c-920d-3a47f4cb5ed4
		summarizeBy: none
		sourceColumn: WBS Element LV2

		annotation SummarizationSetBy = Automatic

	column 'WBS LV2 Description'
		dataType: string
		lineageTag: 8a9d8902-3de0-4939-9e57-0dff537604ea
		summarizeBy: none
		sourceColumn: WBS LV2 Description

		annotation SummarizationSetBy = Automatic

	column 'Cost Cat Adjust'
		dataType: string
		lineageTag: ba836feb-4edc-4cce-ab32-fdc45a2f16a8
		summarizeBy: none
		sourceColumn: Cost Cat Adjust

		annotation SummarizationSetBy = Automatic

	column Costs/Val
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a66bd5b9-f35b-4aee-af42-9f6124d181bd
		summarizeBy: sum
		sourceColumn: Costs/Val

		annotation SummarizationSetBy = Automatic

	column 'Cost element name'
		dataType: string
		lineageTag: f91c71c5-bf04-4991-a3b5-3e433e31af70
		summarizeBy: none
		sourceColumn: Cost element name

		annotation SummarizationSetBy = Automatic

	column 'Purchasing Document'
		dataType: string
		lineageTag: 00619a71-d91f-45e7-864e-458daefa20df
		summarizeBy: none
		sourceColumn: Purchasing Document

		annotation SummarizationSetBy = Automatic

	column Supplier
		dataType: string
		lineageTag: 7e89730f-af8e-4c8c-aa0a-44919d54a6f1
		summarizeBy: none
		sourceColumn: Supplier

		annotation SummarizationSetBy = Automatic

	column 'Vendor Name'
		dataType: string
		lineageTag: aab043ff-5942-466d-b252-5a2985a74303
		summarizeBy: none
		sourceColumn: Vendor Name

		annotation SummarizationSetBy = Automatic

	column 'From Period'
		dataType: string
		lineageTag: 1845ab50-95e5-4c0d-9695-a40bbdc58dc6
		summarizeBy: none
		sourceColumn: From Period

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 515bccf6-5307-409c-b371-254614b708d4
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Partner object'
		dataType: string
		lineageTag: 82692ea7-c29d-4154-a661-03950e5ae80c
		summarizeBy: none
		sourceColumn: Partner object

		annotation SummarizationSetBy = Automatic

	column 'CO partner object name'
		dataType: string
		lineageTag: 3dda4e6a-dd30-4660-87ca-7343333c1ba3
		summarizeBy: none
		sourceColumn: CO partner object name

		annotation SummarizationSetBy = Automatic

	column 'Personnel Number'
		dataType: string
		lineageTag: a96faf2b-33ef-4276-9a36-85b8a791dcb4
		summarizeBy: none
		sourceColumn: Personnel Number

		annotation SummarizationSetBy = Automatic

	column 'Document Number'
		dataType: string
		lineageTag: dc252021-7132-4259-8cf1-8e91b841680c
		summarizeBy: none
		sourceColumn: Document Number

		annotation SummarizationSetBy = Automatic

	column 'Name of offsetting account'
		dataType: string
		lineageTag: 722f6553-186d-47c7-840b-792db0107325
		summarizeBy: none
		sourceColumn: Name of offsetting account

		annotation SummarizationSetBy = Automatic

	column 'Document Header Text'
		dataType: string
		lineageTag: 1f35d25d-7a15-477c-bd1e-3ff8522f7ce9
		summarizeBy: none
		sourceColumn: Document Header Text

		annotation SummarizationSetBy = Automatic

	column 'Total quantity'
		dataType: double
		lineageTag: f7aad631-1d3e-4b80-9940-ba9042813560
		summarizeBy: sum
		sourceColumn: Total quantity

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aux. acct assignment_1'
		dataType: string
		lineageTag: 7f056063-1a71-47a0-8ce9-4a9ea018a016
		summarizeBy: none
		sourceColumn: Aux. acct assignment_1

		annotation SummarizationSetBy = Automatic

	column 'Business Transaction'
		dataType: string
		lineageTag: a0184784-083d-41c3-9c2d-74d71178a763
		summarizeBy: none
		sourceColumn: Business Transaction

		annotation SummarizationSetBy = Automatic

	column 'CO area currency'
		dataType: string
		lineageTag: 7c6ba11b-47fe-446c-b23d-34c5ecc30451
		summarizeBy: none
		sourceColumn: CO area currency

		annotation SummarizationSetBy = Automatic

	column 'Company Code'
		dataType: string
		lineageTag: 8048cbde-a4d7-4d5c-808a-d62d952a1840
		summarizeBy: none
		sourceColumn: Company Code

		annotation SummarizationSetBy = Automatic

	column 'Created on'
		dataType: string
		lineageTag: 0b188ee1-5087-44da-b09e-46fb0cc0f6b1
		summarizeBy: none
		sourceColumn: Created on

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 32d5eb7f-2e61-4219-a0a4-d9806c09b11e
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: d4a262e5-b0d4-4315-9807-4ab809322ae3
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Debit type'
		dataType: string
		lineageTag: f33f823d-a2d4-42d6-bd0d-28c2289188aa
		summarizeBy: none
		sourceColumn: Debit type

		annotation SummarizationSetBy = Automatic

	column 'Document type'
		dataType: string
		lineageTag: d12d84ea-919a-485a-b3eb-b7ee75d7ac79
		summarizeBy: none
		sourceColumn: Document type

		annotation SummarizationSetBy = Automatic

	column 'Dr/Cr indicator'
		dataType: string
		lineageTag: d5c15f7d-664e-40e5-acc7-04747a7e2d1a
		summarizeBy: none
		sourceColumn: Dr/Cr indicator

		annotation SummarizationSetBy = Automatic

	column 'Exchange Rate Type'
		dataType: string
		lineageTag: 22693e2e-bf8b-469a-9abb-6ba675a553fe
		summarizeBy: none
		sourceColumn: Exchange Rate Type

		annotation SummarizationSetBy = Automatic

	column 'FI Posting Item'
		dataType: string
		lineageTag: 83f55c33-57b7-4ed7-baf2-5360662764e4
		summarizeBy: none
		sourceColumn: FI Posting Item

		annotation SummarizationSetBy = Automatic

	column 'Functional Area'
		dataType: string
		lineageTag: d71c56b2-6717-4868-84f3-5cdf7caeeb59
		summarizeBy: none
		sourceColumn: Functional Area

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: caf29847-9e00-4450-89e5-5375b8b74fca
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Ledger
		dataType: string
		lineageTag: bf04c4b3-79de-4476-86a2-1919dae25756
		summarizeBy: none
		sourceColumn: Ledger

		annotation SummarizationSetBy = Automatic

	column 'Log. system source'
		dataType: string
		lineageTag: 7816e062-0ee8-4f18-9078-e74d5a7fecaf
		summarizeBy: none
		sourceColumn: Log. system source

		annotation SummarizationSetBy = Automatic

	column 'Logical System'
		dataType: string
		lineageTag: ac9f030e-9df9-4ec8-b4ed-2d64a9712f59
		summarizeBy: none
		sourceColumn: Logical System

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		lineageTag: 70ed91fd-dcac-416b-b11a-27b39c04439b
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Material Description'
		dataType: string
		lineageTag: ae28d81a-a3c3-4e91-b025-39a8590791f5
		summarizeBy: none
		sourceColumn: Material Description

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 661cb80d-0f80-4101-8788-093cb526e554
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Name of offsetting account_1'
		dataType: string
		lineageTag: bdace7d7-5e40-4649-8959-9d18750985f5
		summarizeBy: none
		sourceColumn: Name of offsetting account_1

		annotation SummarizationSetBy = Automatic

	column Object
		dataType: string
		lineageTag: e44613d9-53a7-4597-a5ec-9cc45a61123f
		summarizeBy: none
		sourceColumn: Object

		annotation SummarizationSetBy = Automatic

	column 'Object Currency'
		dataType: string
		lineageTag: 3b94f947-fb71-4ad9-bda5-6a7712cf8d08
		summarizeBy: none
		sourceColumn: Object Currency

		annotation SummarizationSetBy = Automatic

	column 'Object type'
		dataType: string
		lineageTag: 77763eaf-8752-481e-add9-b9987e4d12a4
		summarizeBy: none
		sourceColumn: Object type

		annotation SummarizationSetBy = Automatic

	column 'Object type_2'
		dataType: string
		lineageTag: 5e95af33-1098-4a59-9442-235f736f7299
		summarizeBy: none
		sourceColumn: Object type_2

		annotation SummarizationSetBy = Automatic

	column 'Offsetting account type'
		dataType: string
		lineageTag: fbee6272-9f9c-4501-9ba5-4b3d8acfbe9b
		summarizeBy: none
		sourceColumn: Offsetting account type

		annotation SummarizationSetBy = Automatic

	column 'Offsetting acct no.'
		dataType: string
		lineageTag: b8506f7e-35dc-4982-b95a-af9a787a0fb3
		summarizeBy: none
		sourceColumn: Offsetting acct no.

		annotation SummarizationSetBy = Automatic

	column 'Origin-obj. type'
		dataType: string
		lineageTag: 5d4fe994-6d14-49e5-b5de-cb884955767a
		summarizeBy: none
		sourceColumn: Origin-obj. type

		annotation SummarizationSetBy = Automatic

	column 'Original bus. trans'
		dataType: string
		lineageTag: 78d2998e-faaa-4ef1-82e5-1c5aebb99c83
		summarizeBy: none
		sourceColumn: Original bus. trans

		annotation SummarizationSetBy = Automatic

	column ParActivity
		dataType: string
		lineageTag: d58146e3-6d7b-45e1-b725-8fb37a6d696b
		summarizeBy: none
		sourceColumn: ParActivity

		annotation SummarizationSetBy = Automatic

	column 'Parked by'
		dataType: string
		lineageTag: 7ad8e673-f3dd-40cd-84b7-3d2c308303ed
		summarizeBy: none
		sourceColumn: Parked by

		annotation SummarizationSetBy = Automatic

	column 'Partner CoCode'
		dataType: string
		lineageTag: 0bb81a28-f2fb-45cb-910f-efeb3a251336
		summarizeBy: none
		sourceColumn: Partner CoCode

		annotation SummarizationSetBy = Automatic

	column 'Partner Func. Area'
		dataType: string
		lineageTag: f0c5f641-8226-45c0-a410-5d92a0a421e5
		summarizeBy: none
		sourceColumn: Partner Func. Area

		annotation SummarizationSetBy = Automatic

	column 'Partner Object Class'
		dataType: string
		lineageTag: 4a7e2fda-4754-4306-a9eb-1e9adce2c790
		summarizeBy: none
		sourceColumn: Partner Object Class

		annotation SummarizationSetBy = Automatic

	column 'Partner object type'
		dataType: string
		lineageTag: 20bb8eaf-0536-441c-af0d-fa00993abf6e
		summarizeBy: none
		sourceColumn: Partner object type

		annotation SummarizationSetBy = Automatic

	column 'Partner object type_3'
		dataType: string
		lineageTag: 8f40fcc8-5cd1-4b02-abdb-b56b38950909
		summarizeBy: none
		sourceColumn: Partner object type_3

		annotation SummarizationSetBy = Automatic

	column 'Partner Segment'
		dataType: string
		lineageTag: 5a1dd1be-4c5d-4401-9d17-3cec756eb0f3
		summarizeBy: none
		sourceColumn: Partner Segment

		annotation SummarizationSetBy = Automatic

	column 'Cost Center'
		dataType: string
		lineageTag: 079fd105-2c83-443a-946f-4e459caf9076
		summarizeBy: none
		sourceColumn: Cost Center

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 742f7497-a06c-4e60-882b-522765457a3a
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 101aa5a6-428f-4d54-b784-e98a15d2e823
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Posted unit of meas.'
		dataType: string
		lineageTag: 54c256b7-a466-468c-a95b-62471ab60f8e
		summarizeBy: none
		sourceColumn: Posted unit of meas.

		annotation SummarizationSetBy = Automatic

	column 'Posting row'
		dataType: string
		lineageTag: 8be6e158-ebb3-4f9e-9e8e-4ede010d3710
		summarizeBy: none
		sourceColumn: Posting row

		annotation SummarizationSetBy = Automatic

	column 'Posting row_4'
		dataType: string
		lineageTag: 30e89964-9034-4101-803e-fdc6afeebeaf
		summarizeBy: none
		sourceColumn: Posting row_4

		annotation SummarizationSetBy = Automatic

	column 'Proj.type'
		dataType: string
		lineageTag: 1c0585c3-8fa9-4d6d-8a53-79713bb5e342
		summarizeBy: none
		sourceColumn: Proj.type

		annotation SummarizationSetBy = Automatic

	column 'Purchase order text'
		dataType: string
		lineageTag: 946b1a66-57bb-48af-abaf-2e367d03281e
		summarizeBy: none
		sourceColumn: Purchase order text

		annotation SummarizationSetBy = Automatic

	column 'Ref Document Number'
		dataType: string
		lineageTag: 4ace401b-70be-4f49-a77e-d88e88acdcd2
		summarizeBy: none
		sourceColumn: Ref Document Number

		annotation SummarizationSetBy = Automatic

	column 'Ref. company code'
		dataType: string
		lineageTag: 0098ce07-fb07-4fc2-9cf7-a489e915f1e5
		summarizeBy: none
		sourceColumn: Ref. company code

		annotation SummarizationSetBy = Automatic

	column 'Ref. fiscal year'
		dataType: string
		lineageTag: a9d815c4-ed82-499e-a5a8-8ead3dc3df16
		summarizeBy: none
		sourceColumn: Ref. fiscal year

		annotation SummarizationSetBy = Automatic

	column 'Ref.document type'
		dataType: string
		lineageTag: 5f602a4c-28cd-440b-aded-0a7e94adf18a
		summarizeBy: none
		sourceColumn: Ref.document type

		annotation SummarizationSetBy = Automatic

	column 'Reference Org Unit'
		dataType: string
		lineageTag: 423ddfd8-ca93-4a46-ae71-c98714e075dd
		summarizeBy: none
		sourceColumn: Reference Org Unit

		annotation SummarizationSetBy = Automatic

	column 'Reference Transact.'
		dataType: string
		lineageTag: 2ef006b5-8fed-4f6d-9b61-d74538340f0e
		summarizeBy: none
		sourceColumn: Reference Transact.

		annotation SummarizationSetBy = Automatic

	column 'Report currency'
		dataType: string
		lineageTag: 887f0c54-ceb2-4df6-a317-d1481cde52e6
		summarizeBy: none
		sourceColumn: Report currency

		annotation SummarizationSetBy = Automatic

	column 'Reversal document'
		dataType: string
		lineageTag: 19579ae3-e3e3-4d58-98e9-a4187c403806
		summarizeBy: none
		sourceColumn: Reversal document

		annotation SummarizationSetBy = Automatic

	column 'Reversal organizatn'
		dataType: string
		lineageTag: fcd8c1fe-af46-470b-abc7-3fec61349d02
		summarizeBy: none
		sourceColumn: Reversal organizatn

		annotation SummarizationSetBy = Automatic

	column 'Reversal referen.no.'
		dataType: string
		lineageTag: babbff5f-6a36-408a-86e8-82f844594d80
		summarizeBy: none
		sourceColumn: Reversal referen.no.

		annotation SummarizationSetBy = Automatic

	column Reversed
		dataType: string
		lineageTag: 53d54e3f-5edb-4179-80f5-3dbb95e86919
		summarizeBy: none
		sourceColumn: Reversed

		annotation SummarizationSetBy = Automatic

	column 'Row in op. version'
		dataType: string
		lineageTag: 477b956d-00cc-44f3-8bf6-97c4c5f5bbff
		summarizeBy: none
		sourceColumn: Row in op. version

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: e962c888-cf1a-40f3-96bd-807783fce6d0
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Source Object'
		dataType: string
		lineageTag: 680437ec-f0d7-44bf-938c-f8fd28160a4e
		summarizeBy: none
		sourceColumn: Source Object

		annotation SummarizationSetBy = Automatic

	column 'Source object name'
		dataType: string
		lineageTag: 1a86c687-2d74-41a9-b8a7-fae71cd2007b
		summarizeBy: none
		sourceColumn: Source object name

		annotation SummarizationSetBy = Automatic

	column 'Source object type'
		dataType: string
		lineageTag: 9d034c89-e07b-4899-995e-bbfc1f20ecd0
		summarizeBy: none
		sourceColumn: Source object type

		annotation SummarizationSetBy = Automatic

	column 'Time created'
		dataType: string
		lineageTag: e313c94a-eac7-497f-a5f6-a99d9558fd0e
		summarizeBy: none
		sourceColumn: Time created

		annotation SummarizationSetBy = Automatic

	column 'Time of Entry'
		dataType: string
		lineageTag: 4a2d67da-8ecd-451d-9bc9-7be4e0ea4769
		summarizeBy: none
		sourceColumn: Time of Entry

		annotation SummarizationSetBy = Automatic

	column 'To Period'
		dataType: string
		lineageTag: ff383c81-025d-4ca0-a789-f84a86d412a0
		summarizeBy: none
		sourceColumn: To Period

		annotation SummarizationSetBy = Automatic

	column 'Total Quantity.1'
		dataType: double
		lineageTag: 18a919f2-8d0a-4a2f-b344-47dc5195eeb6
		summarizeBy: sum
		sourceColumn: Total Quantity.1

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Transaction Currency'
		dataType: string
		lineageTag: c1aa34a6-530c-4144-ab39-6a25c474d403
		summarizeBy: none
		sourceColumn: Transaction Currency

		annotation SummarizationSetBy = Automatic

	column 'Unit of Measure'
		dataType: string
		lineageTag: 3a28ccb9-0d8f-49cc-8e7f-4763d601bb07
		summarizeBy: none
		sourceColumn: Unit of Measure

		annotation SummarizationSetBy = Automatic

	column 'User Name'
		dataType: string
		lineageTag: 139adf26-2b0f-4afa-9b67-211bcff7a04a
		summarizeBy: none
		sourceColumn: User Name

		annotation SummarizationSetBy = Automatic

	column 'Val.in rep.cur.'
		dataType: string
		lineageTag: 7186c58a-e1b5-4b55-9633-764acf1cd091
		summarizeBy: none
		sourceColumn: Val.in rep.cur.

		annotation SummarizationSetBy = Automatic

	column 'value date'
		dataType: string
		lineageTag: 35a2ed9b-4113-4682-93ce-ff2ce808a06f
		summarizeBy: none
		sourceColumn: value date

		annotation SummarizationSetBy = Automatic

	column 'Value in Obj. Crcy'
		dataType: string
		lineageTag: 684de4e5-53f7-4845-82d6-8436661893e2
		summarizeBy: none
		sourceColumn: Value in Obj. Crcy

		annotation SummarizationSetBy = Automatic

	column 'Value TranCurr'
		dataType: string
		lineageTag: c6d086bf-c97f-4235-b1f6-0c5909c90cb2
		summarizeBy: none
		sourceColumn: Value TranCurr

		annotation SummarizationSetBy = Automatic

	column 'Value Type'
		dataType: string
		lineageTag: 823ae2ad-b112-4e40-991f-ebb5bca29dd2
		summarizeBy: none
		sourceColumn: Value Type

		annotation SummarizationSetBy = Automatic

	column 'Var.val.in rep.cur.'
		dataType: string
		lineageTag: 09fa4033-f275-4659-9304-3b7280466a7a
		summarizeBy: none
		sourceColumn: Var.val.in rep.cur.

		annotation SummarizationSetBy = Automatic

	column 'Vbl. value/Obj. curr'
		dataType: string
		lineageTag: c29bad8c-2df8-42cc-8817-b53693ff195b
		summarizeBy: none
		sourceColumn: Vbl. value/Obj. curr

		annotation SummarizationSetBy = Automatic

	column 'Vbl. value/TranCurr.'
		dataType: string
		lineageTag: 14177b19-8735-44d6-a611-a7644f261ed1
		summarizeBy: none
		sourceColumn: Vbl. value/TranCurr.

		annotation SummarizationSetBy = Automatic

	column 'Vbl.Val./COCrcy'
		dataType: string
		lineageTag: 241e085f-2f78-4efe-848a-1f83b9f5276d
		summarizeBy: none
		sourceColumn: Vbl.Val./COCrcy

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: b3e38dd6-a5b6-43b8-8058-9bcb59db673e
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column 'Personnel Number_5'
		dataType: string
		lineageTag: 13397609-f31c-46ac-9afa-543cc4dcc162
		summarizeBy: none
		sourceColumn: Personnel Number_5

		annotation SummarizationSetBy = Automatic

	column 'WBS L1'
		dataType: string
		lineageTag: 994b2c4f-e807-49bb-93b2-c3f42f61b611
		summarizeBy: none
		sourceColumn: WBS L1

		annotation SummarizationSetBy = Automatic

	column 'Cost Cat'
		dataType: string
		lineageTag: 2097c907-61d3-40bb-896b-744cec57c698
		summarizeBy: none
		sourceColumn: Cost Cat

		annotation SummarizationSetBy = Automatic

	column Portfolio
		dataType: string
		lineageTag: 0f1f44c5-0b3a-4f68-86ee-77220b552018
		summarizeBy: none
		sourceColumn: Portfolio

		annotation SummarizationSetBy = Automatic

	column PM
		dataType: string
		lineageTag: 6a6ebf94-6c4b-41a1-81cc-c84c5916ce3f
		summarizeBy: none
		sourceColumn: PM

		annotation SummarizationSetBy = Automatic

	column Acct
		dataType: string
		lineageTag: cb51eeef-c40a-43d6-a037-c1ca90ea6ca5
		summarizeBy: none
		sourceColumn: Acct

		annotation SummarizationSetBy = Automatic

	column 'Cost Element'
		dataType: string
		lineageTag: 3a83126d-5184-47e9-8fcc-93bc8d50b27f
		summarizeBy: none
		sourceColumn: Cost Element

		annotation SummarizationSetBy = Automatic

	column Month = format(fact_Labor_details[Posting Date],"mmm")
		dataType: string
		lineageTag: 9964589f-f91f-4c33-9426-d32b64cfa6b9
		summarizeBy: none
		sortByColumn: Period

		changedProperty = DataType

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Labor type short'
		dataType: string
		lineageTag: d0e8f4b8-3a6b-407a-8761-9e9c75385fe3
		summarizeBy: none
		sourceColumn: Labor type short

		annotation SummarizationSetBy = Automatic

	column 'Budget Hours'
		dataType: string
		lineageTag: 30a347a0-6c93-4f96-8b7f-f3ece839e78c
		summarizeBy: none
		sourceColumn: Budget Hours

		annotation SummarizationSetBy = Automatic

	column Column108
		dataType: string
		lineageTag: 9d0169a5-864d-4142-b90c-157979a02b5d
		summarizeBy: none
		sourceColumn: Column108

		annotation SummarizationSetBy = Automatic

	column Column109
		dataType: string
		lineageTag: 5237c968-a965-429b-946a-22ec2561e137
		summarizeBy: none
		sourceColumn: Column109

		annotation SummarizationSetBy = Automatic

	column Column110
		dataType: string
		lineageTag: 2ac994f3-a1a5-46a7-96b0-a974da1cddc8
		summarizeBy: none
		sourceColumn: Column110

		annotation SummarizationSetBy = Automatic

	column Column111
		dataType: string
		lineageTag: b6b47839-13d7-48e2-a692-9768a37ae1bd
		summarizeBy: none
		sourceColumn: Column111

		annotation SummarizationSetBy = Automatic

	column Column113
		dataType: string
		lineageTag: 593cc848-7060-40ed-a03a-f1db4f9c4b78
		summarizeBy: none
		sourceColumn: Column113

		annotation SummarizationSetBy = Automatic

	column Column112
		dataType: double
		lineageTag: 898bd59c-5a77-44a3-88a5-3596924f0db1
		summarizeBy: sum
		sourceColumn: Column112

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column114
		dataType: string
		lineageTag: 21b2b847-ab0c-437b-a2da-e97923f7a724
		summarizeBy: none
		sourceColumn: Column114

		annotation SummarizationSetBy = Automatic

	column Column115
		dataType: string
		lineageTag: 86d0f94f-c5e3-4998-a380-701cc2abab56
		summarizeBy: none
		sourceColumn: Column115

		annotation SummarizationSetBy = Automatic

	partition fact_Labor_details = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents("https://amtrak.sharepoint.com/sites/CapitalDeliveryNortheast/", [ApiVersion = 15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    General = #"Shared Documents"{[Name="General"]}[Content],
				    #"08-Department_Administrative" = General{[Name="08-Department_Administrative"]}[Content],
				    #"NED Overview Files" = #"08-Department_Administrative"{[Name="NED Overview Files"]}[Content],
				    #"Labor Charges" = #"NED Overview Files"{[Name="Labor Charges"]}[Content],
				    #"Maximo - Hours with Personnel wNames xlsx" = #"Labor Charges"{[Name="Maximo - Hours with Personnel wNames.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Maximo - Hours with Personnel wNames xlsx"),
				    Sheet1_Sheet = #"Imported Excel Workbook"{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Total Quantity", "Total Quantity.1"}, {"CO object name", "WBS LV2 Description"}, {"WBS Element", "WBS Element LV2"}, {"Project Definition", "WBS LV1"}, {"Val/COArea Crcy", "Costs/Val"}, {"Purchasing Document", "Purchasing Document"}, {"Supplier", "Supplier"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true),
				    #"Reordered Columns" = Table.ReorderColumns(#"Filtered Rows",{"Document Date", "Posting Date", "WBS LV1", "WBS Element LV2", "WBS LV2 Description", "Cost Element", "Cost element descr.", "Cost Cat Adjust", "Costs/Val", "Cost element name", "Purchasing Document", "Supplier", "Vendor Name", "From Period", "Fiscal Year", "Partner object", "CO partner object name", "Personnel Number", "Document Number", "Name of offsetting account", "Document Header Text", "Total quantity", "Aux. acct assignment_1", "Business Transaction", "CO area currency", "Company Code", "Created on", "Customer", "Customer Name", "Debit type", "Document type", "Dr/Cr indicator", "Exchange Rate Type", "Functional Area", "Item", "Ledger", "Log. system source", "Logical System", "Material", "Material Description", "Name", "Name of offsetting account_1", "Object", "Object Currency", "Object type", "Object type_2", "Offsetting account type", "Offsetting acct no.", "Origin-obj. type", "Original bus. trans", "ParActivity", "Parked by", "Partner CoCode", "Partner Func. Area", "Partner Object Class", "Partner object type", "Partner object type_3", "Partner Segment", "Partner-CCtr", "Period", "Plant", "Posted unit of meas.", "Posting row", "Posting row_4", "Proj.type", "Purchase order text", "Ref Document Number", "Ref. company code", "Ref. fiscal year", "Ref.document type", "Reference Org Unit", "Reference Transact.", "Report currency", "Reversal document", "Reversal organizatn", "Reversal referen.no.", "Reversed", "Row in op. version", "Segment", "Source Object", "Source object name", "Source object type", "Time created", "Time of Entry", "To Period", "Total Quantity.1", "Transaction Currency", "Unit of Measure", "User Name", "Val.in rep.cur.", "Value date", "Value in Obj. Crcy", "Value TranCurr", "Value Type", "Var.val.in rep.cur.", "Vbl. value/Obj. curr", "Vbl. value/TranCurr.", "Vbl.Val./COCrcy", "Version", "Personnel Number_5", "WBS", "Cost Cat", "Portfolio", "PM", "Acct"}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Reordered Columns", {{"Cost Element", type text}}, "en-US"),{"Cost Element", "Cost element descr."},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Merged"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Merged Columns",{{"Merged", "Cost Element"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Costs/Val", Currency.Type}, {"Personnel Number", type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Value date", "value date"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Fiscal Year", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type2","2024","FY24",Replacer.ReplaceText,{"Fiscal Year"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","2025","FY25",Replacer.ReplaceText,{"Fiscal Year"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value1", each ([Cost element name] = "OVERTIME" or [Cost element name] = "TPNW - OTHER WAGES" or [Cost element name] = "WAGES -STRAIGHT TIME")),
				    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows1","WAGES -STRAIGHT TIME","STRAIGHT TIME",Replacer.ReplaceText,{"Cost element name"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Replaced Value2",{{"Partner-CCtr", "Cost Center"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns3", "Cost element name", "Cost element name - Copy"),
				    #"Renamed Columns4" = Table.RenameColumns(#"Duplicated Column",{{"Cost element name - Copy", "Labo type short"}}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Renamed Columns4","OVERTIME","OT",Replacer.ReplaceText,{"Labo type short"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","STRAIGHT TIME","ST",Replacer.ReplaceText,{"Labo type short"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Replaced Value4",{{"Labo type short", "Labor type short"}}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Renamed Columns5","TPNW - OTHER WAGES","TPNW",Replacer.ReplaceText,{"Labor type short"}),
				    #"Renamed Columns6" = Table.RenameColumns(#"Replaced Value5",{{"WBS", "WBS L1"}})
				in
				    #"Renamed Columns6"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

